#!env bash

eval $(docker-machine env local)

docker run -t -i --rm -v ~/src/technical-blog:/mnt/blog jmooredocker/jbake:v1.0.0 /opt/jbake/bin/jbake -b /mnt/blog/input /mnt/blog/output

docker run -p 8820:8820 -t -i --rm -v ~/src/technical-blog:/mnt/blog jmooredocker/jbake:v1.0.0 /opt/jbake/bin/jbake -s /mnt/blog/output
